### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by if22** [famzah/google-sites-backup#2]
Hey,
Thanks for your utility!
I faced off some problem. 

Next page to fetch from the API? Yes.
gdata-backup//a/domain.com/wiki/testovaa-stranica/fdg/dsfh/1.html (Entity - announcementspage)
gdata-backup//a/domain.com/wiki/testovaa-stranica/fdg/dsfh/__meta/1.txt (Meta - announcementspage)
gdata-backup//feeds/content/domain.com/wiki/1298546007443993809/1121744646650675806.txt (Entity - listitem)
gdata-backup//feeds/content/domain.com/wiki/1298546007443993809/__meta/1121744646650675806.txt (Meta - listitem)
gdata-backup//feeds/content/domain.com/wiki/8021790685155168024/1448610017716212498.txt (Entity - listitem)
gdata-backup//feeds/content/domain.com/wiki/8021790685155168024/__meta/1448610017716212498.txt (Meta - listitem)
gdata-backup//feeds/content/domain.com/wiki/8021790685155168024/1894479626184834421.txt (Entity - listitem)
gdata-backup//feeds/content/domain.com/wiki/8021790685155168024/__meta/1894479626184834421.txt (Meta - listitem)
Traceback (most recent call last):
  File "/home/user/backup/google-sites-backup//backup.py", line 688, in <module>
    main()
  File "/home/user/backup/google-sites-backup//backup.py", line 685, in main
    backup.Run()
  File "/home/user/backup/google-sites-backup//backup.py", line 677, in Run
    id_to_pub_href = self.ProcessFeedEntries(destdir) # HTTP transfers
  File "/home/user/backup/google-sites-backup//backup.py", line 556, in ProcessFeedEntries
    self.DumpWebAttachment(entry, out)
  File "/home/user/backup/google-sites-backup//backup.py", line 374, in DumpWebAttachment
    entry.summary.text.encode('utf-8'), entry.content.src.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

Could you please help me with that?

**Comment by famzah** [comment]
Hi Aleks,

Can you provide the debug files which are located in the "__debug" root folder? Please archive them using ZIP, GZIP, etc. and attach them here.

If the website is a private one, you can send them directly to my email, which you can find at http://blog.famzah.net/about/

If none of these options work, I'll modify the backup script to dump the entry where the failure occurs. I should probably do this anyway, but having your debug data locally will speed up the debugging process.

**Comment by if22** [comment]
It's a private site. I sent debug info by email.

**Comment by famzah** [comment]
I believe this should have been fixed now. Please test again and report the outcome. Thanks.

**Comment by if22** [comment]
"Moving list entries into their parent pages...
All done."
Thank you!
