### ISSUE TITLE
HTML pages only partially downloaded

### ISSUE THREAD

**Issue by gioele** [famzah/google-sites-backup#4]
HTML pages downloaded via `google-sites-backup` are truncated after the main content. No content after the first `<div>` is present. This means that the footer and all the closing HTML elements are just not there.

To fetch the pages I used the `run.sh` script as described in the README file.

Let me know if this is reproducible also with other sites, as I have access only to two.

**Comment by famzah** [comment]
Hi,

Please create a sample public Google Site to reproduce the problem. Alternatively, you can grant me read access to one of your sites. Whichever works best for you.

**Comment by gioele** [comment]
I tried other downloader and I realized that the issue is that only part of the delivered HTML page is available via the API. The final page delivered by `sites.google.com` is a mixture of the user-created page (`<div>` available via the API), the template (where the footer is) and other scaffolding.

It looks like there is no way to retrieve all that additional markup short of just downloading the whole page from `sites.google.com`.
